// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Connect(arg1:string,arg2:string):Promise<boolean>;

export function Disconnect(arg1:string,arg2:string):Promise<boolean>;

export function Screenshot(arg1:string):Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;
