// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MatchTemplate(arg1, arg2) {
  return window['go']['main']['Game']['MatchTemplate'](arg1, arg2);
}

export function StartGame() {
  return window['go']['main']['Game']['StartGame']();
}

export function Startup(arg1, arg2) {
  return window['go']['main']['Game']['Startup'](arg1, arg2);
}
