// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {adb} from '../models';

export function StartGame():Promise<void>;

export function Startup(arg1:context.Context,arg2:adb.Adb):Promise<void>;
