// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {image} from '../models';
import {gocv} from '../models';
import {context} from '../models';
import {adb} from '../models';
import {logs} from '../models';

export function ActiveTaskButton():Promise<void>;

export function ActiveTeamButton():Promise<void>;

export function CheckStop():Promise<boolean>;

export function ClickShiYong():Promise<void>;

export function CloseDialog():Promise<void>;

export function CloseLeftArrow():Promise<void>;

export function CloseTeamDialog():Promise<void>;

export function FindXiaoEr():Promise<void>;

export function FindZhengBiaoTou():Promise<void>;

export function FindZhongKui():Promise<void>;

export function GotoChangAn():Promise<void>;

export function HasDialog():Promise<boolean|image.Point>;

export function HasHelper():Promise<boolean>;

export function HasImage(arg1:string):Promise<boolean|image.Point>;

export function HasLiXian():Promise<boolean>;

export function HasPackage():Promise<boolean>;

export function IsBettle():Promise<boolean>;

export function IsHuoDongDialog():Promise<void>;

export function IsTeamDialog():Promise<void>;

export function MatchTemplate(arg1:string,arg2:number):Promise<boolean|image.Point>;

export function MatchTemplateFullGray(arg1:gocv.Mat,arg2:string,arg3:number):Promise<boolean|image.Point>;

export function NeedTeamGuiUp():Promise<boolean>;

export function OpenHuoDongDialog(arg1:string):Promise<void>;

export function OpenPackage():Promise<void>;

export function OpenTeamDialog():Promise<void>;

export function StartBaoTuTask():Promise<void>;

export function StartGame(arg1:boolean,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function StartHuoDongTask(arg1:string,arg2:string):Promise<void>;

export function StartShimenTask():Promise<void>;

export function StartWaBaoTuTask():Promise<void>;

export function StartYunBiao():Promise<void>;

export function Startup(arg1:context.Context,arg2:adb.Adb,arg3:logs.Log):Promise<void>;

export function StopGame():Promise<void>;

export function TeamGuiUp():Promise<void>;

export function TestButton():Promise<void>;
