// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveTaskButton() {
  return window['go']['main']['Game']['ActiveTaskButton']();
}

export function ActiveTeamButton() {
  return window['go']['main']['Game']['ActiveTeamButton']();
}

export function CheckAndClickTimingCancel() {
  return window['go']['main']['Game']['CheckAndClickTimingCancel']();
}

export function CheckStop() {
  return window['go']['main']['Game']['CheckStop']();
}

export function ClickShiYong() {
  return window['go']['main']['Game']['ClickShiYong']();
}

export function CloseDialog() {
  return window['go']['main']['Game']['CloseDialog']();
}

export function CloseLeftArrow() {
  return window['go']['main']['Game']['CloseLeftArrow']();
}

export function CloseTeamDialog() {
  return window['go']['main']['Game']['CloseTeamDialog']();
}

export function ContinueZhuoGui() {
  return window['go']['main']['Game']['ContinueZhuoGui']();
}

export function EditTeamTarget() {
  return window['go']['main']['Game']['EditTeamTarget']();
}

export function FindXiaoEr() {
  return window['go']['main']['Game']['FindXiaoEr']();
}

export function FindZhengBiaoTou() {
  return window['go']['main']['Game']['FindZhengBiaoTou']();
}

export function FindZhongKui() {
  return window['go']['main']['Game']['FindZhongKui']();
}

export function GotoChangAn() {
  return window['go']['main']['Game']['GotoChangAn']();
}

export function HasDialog() {
  return window['go']['main']['Game']['HasDialog']();
}

export function HasHelper() {
  return window['go']['main']['Game']['HasHelper']();
}

export function HasImage(arg1) {
  return window['go']['main']['Game']['HasImage'](arg1);
}

export function HasLiXian() {
  return window['go']['main']['Game']['HasLiXian']();
}

export function HasPackage() {
  return window['go']['main']['Game']['HasPackage']();
}

export function IsBettle() {
  return window['go']['main']['Game']['IsBettle']();
}

export function IsHuoDongDialog() {
  return window['go']['main']['Game']['IsHuoDongDialog']();
}

export function IsTeamDialog() {
  return window['go']['main']['Game']['IsTeamDialog']();
}

export function MatchTemplate(arg1, arg2) {
  return window['go']['main']['Game']['MatchTemplate'](arg1, arg2);
}

export function MatchTemplateFullGray(arg1, arg2, arg3) {
  return window['go']['main']['Game']['MatchTemplateFullGray'](arg1, arg2, arg3);
}

export function NeedTeamGuiUp() {
  return window['go']['main']['Game']['NeedTeamGuiUp']();
}

export function NewTeamGuiUp() {
  return window['go']['main']['Game']['NewTeamGuiUp']();
}

export function OneClickSpeak() {
  return window['go']['main']['Game']['OneClickSpeak']();
}

export function OpenHuoDongDialog(arg1) {
  return window['go']['main']['Game']['OpenHuoDongDialog'](arg1);
}

export function OpenPackage() {
  return window['go']['main']['Game']['OpenPackage']();
}

export function OpenTeamDialog() {
  return window['go']['main']['Game']['OpenTeamDialog']();
}

export function Reset() {
  return window['go']['main']['Game']['Reset']();
}

export function StartBaoTuTask() {
  return window['go']['main']['Game']['StartBaoTuTask']();
}

export function StartGame(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['Game']['StartGame'](arg1, arg2, arg3, arg4, arg5);
}

export function StartHuoDongTask(arg1, arg2) {
  return window['go']['main']['Game']['StartHuoDongTask'](arg1, arg2);
}

export function StartShimenTask() {
  return window['go']['main']['Game']['StartShimenTask']();
}

export function StartWaBaoTuTask() {
  return window['go']['main']['Game']['StartWaBaoTuTask']();
}

export function StartYunBiao() {
  return window['go']['main']['Game']['StartYunBiao']();
}

export function Startup(arg1, arg2, arg3) {
  return window['go']['main']['Game']['Startup'](arg1, arg2, arg3);
}

export function StopGame() {
  return window['go']['main']['Game']['StopGame']();
}

export function TeamGuiUp() {
  return window['go']['main']['Game']['TeamGuiUp']();
}

export function TestButton() {
  return window['go']['main']['Game']['TestButton']();
}
